### PR TITLE
Enh: Add 'inputSpan' integer option to ActiveField

### PR DESCRIPTION
**Pull request by nbogol**
Enhancement. Add 'inputSpan' integer option to the kartik\form\ActiveField. If set, this option will result 'col-<form_device-size>-<inputSpan>' class set for input div wrapper.

### CODE REVIEW

**Comment by kartik-v** [comment]
Some questions (thanks for the PR though)... as this PR may break the layout for some scenarios

- Have you checked it to work with all bootstrap form layouts (**vertical, horizontal** & **inline**)? For example it may not work as intended in horizontal forms - because the input is already wrapped inside a colspan in a **horizontal form**. Similarly, for layout for **inline form** may also be broken.
- This probably may only be needed for **vertical forms**... even for that if you do not have your field inside a `<div class="row">`, it may break the layout.

IMO... the PR can be simplified to just one option:

**Comment by nbogol** [comment]
Kartik, I did some more testing and code inspection:
My code is in effect only when '$form->hasInputCss()' is true. 
And, if you do not explicitly set formConfig.labelSpan, 
it is true only for HORIZONTAL type of the form and my code is executed and works just fine.
But if you set formConfig.labelSpan, it will be executed for INLINE and VERTICAL.
I think formConfig.labelSpan should be disabled for INLINE and VERTICAL form types, because it does not make sense and does not work correctly anyway. (try to set formConfig.labelSpan=2 for VERTICAL form - it will render as horizontal)

**Comment by nbogol** [comment]
Kartik, 
do you have any comments on my response or you do not want to do this. Please let me know.

**Comment by kartik-v** [comment]
Not yet checked on this yet. For horizontal forms the inputSpan is automatically derived based on labelSpan ... is there a reason why you do not want to provide labelSpan?

**Comment by nbogol** [comment]
As I mentioned it does not look good full screen wide inputs for the form like login form.

**Comment by nbogol** [comment]
For VERTICAL form type labelSpan is irrelevant, right?  :

Name
[              ]

**Comment by kartik-v** [comment]
Yes my query was more for horizontal forms - where input span is derived automatically based on label span. Do you wish to override the input span with this use case? Once you confirm will check a bit on this later to see.

**Comment by kartik-v** [comment]
I think the use case for where this is useful is for HORIZONTAL forms when you wish to hide the label. Right? Will check and incorporate this.

**Comment by kartik-v** [comment]
Ok enhancements have been done and you have two options:

- **OPTION 1:** Use my [yii2-builder extension](http://demos.krajee.com/builder) and use [FormGrid Builder](http://demos.krajee.com/builder-details/form-grid) or [Form Builder](http://demos.krajee.com/builder-details/form) to render complex form layouts for various use cases.

- **OPTION 2:** There are two new options added to ActiveField -`contentBeforeInput` and `contentAfterInput`, you can configure that along with `showLabels` to false to set fields side by side for example:

```php
// Address and city side by side for horizontal
$before = '<div class="row"><div class="col-sm-6">';
$after = '</div><div class="
echo $form->field($model, 'address', [
    'contentBeforeInput' =>  '<div class="row"><div class="col-sm-6">',
    'contentAfterInput' =>  '</div><div class="col-sm-6">' .
        $form->field($model, 'city', ['showLabels'=>false])->textInput([
            'options'=>['placeholder'=>'Enter city']
         ]) . '</div></div>'
]);
```

**Pull request merged**
